### ISSUE TITLE
Response validation fails for forest handlers

### ISSUE THREAD

**Issue by jscheffner** [fiws/hapi-forest#7]
I have two problems when using response validation on forest handlers:

* I can't validate the result of `getAll` because joi complains with this error: 'Error: Cannot validate non-object response' 

* I also can't validate the result of `post` because the response includes keys like `__parent`, `isNew` etc. at the time of the validation (but not in the actual result).  Those keys are part of a nested document (I think they're automatically created by mongoose or mongodb).

Is hapi-forest incompatible to hapi's response validation or is it an error on my side. I'd appreciate some help. Thanks.

**Comment by fiws** [comment]
Hi, thanks for the question.

I never used response validation, so there could be some bugs here.

In case of `getAll` it does not support response validation because it [streams the mongodb](https://github.com/fiws/hapi-forest/blob/master/handlers/getAll.js#L38) response instead of buffering.
As workaround you can pass use the `getAllPaginated` handler which does buffer.
It's not the same as `getAll` as it does support pagination, but it just returns all results by default if no `$limit` query parameter is set. So it should be a drop in replacement.

You can use it like this:

```javascript
server.route({
  method: 'GET',
  path: '/some-model',
  handler: {
    forest: { model: Model, type: 'getAllPaginated' },
  },
  // config is only needed if you need CORS
  config: {
    cors: {
      additionalExposedHeaders: ['x-total-count'],
    },
  },
});
```

For post you can try adding `{ skipMongooseHooks: true }` to the handler.

**Comment by jscheffner** [comment]
Thanks for the quick reaction. This solves at least one issue 👍

**Comment by jscheffner** [comment]
The problem is that `post` doesn't use `lean`. That's why it has those mongoose properties. `delete` for example uses `lean` and works just fine.

**Comment by jscheffner** [comment]
Since the other handlers were changed to use `lean` I don't think that's on purpose. If you don't mind I'll create a PR to make `post` lean soonish.

**Comment by jscheffner** [comment]
My mistake, create isn't a query, so it doesn't have a `lean` method. For consistency one could use .toObject() though but I can also do so in `transformResponse`.

**Comment by fiws** [comment]
thanks for the research. So `skipMongooseHooks: true` does not work? it still has the props with that?

**Comment by jscheffner** [comment]
No. That doesn't help. But this does:

````
server.route({
  method: 'POST',
  path: '/some-model',
  handler: {
    forest: { model: Model,
    transformResponse (result, req) {
        return result.toObject()
    }
  },
});
````

**Comment by fiws** [comment]
after reading the docs i don't think `skipMongooseHooks` even does what it promises.

so i think we discovered 2 bugs here:
* `skipMongooseHooks` does not work
* all handlers return lean objects but post does not

**Comment by jscheffner** [comment]
I only tried out the `skipMongooseHooks` option with v0.5. Maybe it doesn't have the option yet.
